aug:
  image_aug: true
  masked_language_model: true
dataloader:
  num_workers: 0
  pin_memory: true
dataset:
  data_root: mc_ocr/data/folds\fold_2
  image_height: 32
  image_max_width: 512
  image_min_width: 32
  name: data
  train_annotation: mc_ocr/data/folds\fold_2\training_ocr_data/train/train_ocr_fixed.txt
  train_data_root: mc_ocr/data/folds\fold_2\training_ocr_data/train/images
  valid_annotation: mc_ocr/data/folds\fold_2\training_ocr_data/val/val_ocr_fixed.txt
  valid_data_root: mc_ocr/data/folds\fold_2\training_ocr_data/val/images
device: cuda
optimizer:
  max_lr: 0.0003
  pct_start: 0.1
predictor:
  beamsearch: false
quiet: false
seq_modeling: transformer
trainer:
  batch_size: 16
  checkpoint: mc_ocr/data/folds\fold_2\checkpoint.pth
  export: ./weights/transformerocr.pth
  iters: 100000
  log: mc_ocr/data/folds\fold_2\train.log
  metrics: null
  print_every: 200
  valid_every: 4000
transformer:
  d_model: 256
  dim_feedforward: 2048
  max_seq_length: 1024
  nhead: 8
  num_decoder_layers: 6
  num_encoder_layers: 6
  pos_dropout: 0.1
  trans_dropout: 0.1
vocab: "aA\xE0\xC0\u1EA3\u1EA2\xE3\xC3\xE1\xC1\u1EA1\u1EA0\u0103\u0102\u1EB1\u1EB0\
  \u1EB3\u1EB2\u1EB5\u1EB4\u1EAF\u1EAE\u1EB7\u1EB6\xE2\xC2\u1EA7\u1EA6\u1EA9\u1EA8\
  \u1EAB\u1EAA\u1EA5\u1EA4\u1EAD\u1EACbBcCdD\u0111\u0110eE\xE8\xC8\u1EBB\u1EBA\u1EBD\
  \u1EBC\xE9\xC9\u1EB9\u1EB8\xEA\xCA\u1EC1\u1EC0\u1EC3\u1EC2\u1EC5\u1EC4\u1EBF\u1EBE\
  \u1EC7\u1EC6fFgGhHiI\xEC\xCC\u1EC9\u1EC8\u0129\u0128\xED\xCD\u1ECB\u1ECAjJkKlLmMnNoO\xF2\
  \xD2\u1ECF\u1ECE\xF5\xD5\xF3\xD3\u1ECD\u1ECC\xF4\xD4\u1ED3\u1ED2\u1ED5\u1ED4\u1ED7\
  \u1ED6\u1ED1\u1ED0\u1ED9\u1ED8\u01A1\u01A0\u1EDD\u1EDC\u1EDF\u1EDE\u1EE1\u1EE0\u1EDB\
  \u1EDA\u1EE3\u1EE2pPqQrRsStTuU\xF9\xD9\u1EE7\u1EE6\u0169\u0168\xFA\xDA\u1EE5\u1EE4\
  \u01B0\u01AF\u1EEB\u1EEA\u1EED\u1EEC\u1EEF\u1EEE\u1EE9\u1EE8\u1EF1\u1EF0vVwWxXyY\u1EF3\
  \u1EF2\u1EF7\u1EF6\u1EF9\u1EF8\xFD\xDD\u1EF5\u1EF4zZ0123456789!\"#$%&'()*+,-./:;<=>?@[\\\
  ]^_`{|}~ "
