# pretrain: 
#     id_or_url: 13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA
#     md5: af6b46e9295eb1c27ca90bddf8c8729a
#     cached: /tmp/tranformerorc.pth

# url or local path
# weights: C:\Users\hongt\OneDrive\Desktop\Thesis\MC_OCR\mc_ocr\text_classifier\vietocr\config\vgg_transformer.pth
weights: /content/drive/MyDrive/Bachelor of Data Science (IU)/Thesis/code/config/vgg_transformer.pth

backbone: vgg19_bn
cnn:
    pretrained: True
    # pooling stride size
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]         
    # pooling kernel size 
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # dim of ouput feature map
    hidden: 256

